# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "chanyoung ahn"
repo_name: "robotics-paper-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 20

publish_readme: True
publish_gitpage: True

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'

# keywords to search
keywords:
    "Dexterous":
        filters: ["Dexterous Manipulation", "Dexterous hand", "Multifingered", "Multi-fingered", 
                    "Anthropomorphic", "In-hand Manipulation", "Tactile sensing", "Bimanual", "Manipulation"]
    "Manipulation":
        filters: ["Robot Manipulation", "Robotic Manipulation", "Robot Learning", 
                    "Imitation Learning", "Deformable", "Teleoperation", "Learning from Demonstration"]
    "VLA":
        filters: ["Vision Language Action","Vision-Language-Action"]
